name: Discord CI

on:
  push:
    branches:
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build dependencies
      run: |
        mvn install:install-file -Dfile=./lib/GemsEconomy-4.8.3.jar -DgroupId=me.xanium -DartifactId=GemsEconomy -Dversion=4.8.3 -Dpackaging=jar
        mvn install:install-file -Dfile=./lib/PlayerPoints.jar -DgroupId=org.black_ixx -DartifactId=PlayerPoints -Dversion=2.1.4 -Dpackaging=jar
    - name: Build with Maven
      run: |
        cd ./WarpSystem
        mvn clean package
        cd ../
    - name: Check for Signatures on VirusTotal
      run: |
        file=$(find "./WarpSystem/WarpSystem-Bundle-Free/target" -type f -name "WarpSystem_v*.jar" | head -n 1)
        key=${{ secrets.VIRUSTOTAL }}

        echo "Checking for virus detection..."

        url='https://www.virustotal.com/vtapi/v2/file/scan'
        response=$(curl -F apikey=$key -F file=@$file $url)

        resource=$(echo "$response" | jq -r '.resource')
        msg=$(echo "$response" | jq -r '.verbose_msg')

        if [ "$resource" = null ]
        then
          echo "::error::Could not run VirusTotal check. Message: $msg"
        else
          echo "Retrieving scan for resource '$resource'..."
        
          while
            if [ -n "$response_code" ]
            then
              sleep 25
            fi
        
            url='https://www.virustotal.com/vtapi/v2/file/report'
            response=$(curl -F apikey=$key -F resource="$resource" $url)
        
            response_code=$(echo "$response" | jq -r '.response_code')
            [ ! "$response_code" = "1" ]
          do :; done
        
          positives=$(echo "$response" | jq -r '.positives')
          link=$(echo "$response" | jq -r '.permalink')
        
          if [ "$positives" = "0" ]
          then
            echo "No virus detected."
            exit 0
          else
            echo "$positives virus(es) detected! Link: $link"
            exit 1
          fi
        fi
